language: java


env:
  global:
    - secure: "dQDx5aIzwhOauhLhKYiIAbxrbyBN30Y0KqdrkLfNmUM7gYd+8uSCHmeFJnkXu9GCQNx2dpkKBJtty54fSoTz8uHJgWn6sjG8V0A6t5b3AaXo2XYSL3P0xi3AHiJ44xPr1hZOnoX1OiuUV0a6W8DEnmbCCUWApZtleuEvmxDgSjw="
    - secure: "LVU6+H1PWtOKOuZO5Y5tRC2TFsLJpVLvfMCIm9jVHHhB1xtjbNWT34PbrEXtEFwEIrcj9VsxRKmetuS8cp2n3yD6uQlIXslfQVqSgjX0FiQDpDENdgj9qrIC1YtH8AcmAj8gS1tPgCpQfKbJx9Rp0hdmgOzLFglvGqg6VHm9Yo0="
    - secure: "Za9CMIlBPrT2G/8cluiVz+B71+pSelkcy6cPSSruRzKMUsZY15reaJy4mH4nWyAzTcSzC7Pd8YuiGDPHsbdtrVVKYRUtLZ+qJ2wm2iXjgFrC2JQBClQnQ+XNimvv1+zIgJunqTLBSV9flGLK+M9oJupg1rjXGyPCWWbHuoUP2Ps="

before_install:
  - sudo apt-get update
  - sudo apt-get install gnupg openssl -y
  - gpg --list-keys
  - openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in keystores/secring.gpg.enc -out keystores/local.secring.gpg -d
  - openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in keystores/pubring.gpg.enc -out keystores/local.pubring.gpg -d
  - openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in keystores/settings.xml.enc -out keystores/local.settings.xml -d
  - openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in keystores/settings-security.xml.enc -out keystores/local.settings-security.xml -d
  - mv -f keystores/local.secring.gpg ~/.gnupg/secring.gpg
  - mv -f keystores/local.pubring.gpg ~/.gnupg/pubring.gpg
  - gpg --list-keys
  - mv -f keystores/local.settings.xml ~/.m2/settings.xml
  - mv -f keystores/local.settings-security.xml ~/.m2/settings-security.xml
  - cd server

install: mvn deploy -PcodeQuality,sonatype-oss-release -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Psonatype-oss-release -Dgpg.passphrase=$GPG_PASSPHRASE

script: mvn test -B

jdk:
  - oraclejdk8

notifications:
  hipchat:
    on_success: always
    on_failure: always
    notify: true
    format: html
    rooms:
      secure: "KsNXiU3yUR53GzXqdBJETAv7nnpMnkcJmKyvW3M6mlZFQiCjwEYY/wtJAasIWQxeyl06oZSlAcCkXpvGGo43+nGh+aaW+rlcL1XwIE05sZmknfiBivwK2RZIdqkYrwGSofgZkSrgC5NjJAKYPQeRyMtTYoGrn17raRAdKOF+rIU="
