language: java

before_install:
 - cd server

install: mvn install -PcodeQuality -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script: mvn test -B

jdk:
  - oraclejdk8

notifications:
  hipchat:
    on_success: always
    on_failure: always
    notify: true
    format: html
    rooms:
      secure: "KsNXiU3yUR53GzXqdBJETAv7nnpMnkcJmKyvW3M6mlZFQiCjwEYY/wtJAasIWQxeyl06oZSlAcCkXpvGGo43+nGh+aaW+rlcL1XwIE05sZmknfiBivwK2RZIdqkYrwGSofgZkSrgC5NjJAKYPQeRyMtTYoGrn17raRAdKOF+rIU="
